import Head from 'next/head'
import Image from 'next/image'

import ChannelCard from '../components/ChannelCard'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Proplay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-wrap justify-around '>
        <h1>Hola</h1>
      </div>
    </div>
  )
}
