import Head from 'next/head'
import Image from 'next/image'

import VideoPreview from '../components/VideoPreview'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Proplay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-wrap justify-around '>
        <VideoPreview />
        <VideoPreview />
        <VideoPreview />
        <VideoPreview />
        <VideoPreview />
        <VideoPreview />
      </div>
    </div>
  )
}
