import Head from 'next/head'
import Link from 'next/link'
import Feed from '../../components/Feed'
import { useContext } from 'react'
import { AppContext } from '../../context/AppContext'
import { useRouter } from 'next/router'

import { categories } from '../../utils/constants'


export default function Discover() {
  const { setLocation } = useContext(AppContext)
  const {pathname} = useRouter()
  setLocation(pathname)

  return (
    <div className=''>
      <Head>
        <title>Discover</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-screen grid p-10 gap-8 grid-cols-1 md:grid-cols-2 md:w-full xl:grid-cols-4 justify-around '>
        {categories.map((category, index) => (
          <Link href={`/search/${category.name}`} key={index}>
          <div className="py-10 px-6 rounded-2xl flex items-center bg-selected cursor-pointer hover:shadow-lg hover:shadow-red-600/5 transition-transform hover:scale-105">
            <span className='text-2xl mr-4'>{category.icon}</span>
            <h1 className='text-xl font-bold'>{category.name}</h1>
          </div>
          </Link>
        ))}
      </div>
    </div>
  )
}